### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mgree** [mgree/js2ts#1]
- [ ] expand AST
  + [x] operations
  + [x] variable declarations
  + [x] control flow
    + [ ] `strengthen` to 'truthy' values
  + [ ] function definitions
  + [ ] function calls
- [x] no need to track types on AST nodes (but _do_ track function argument and return types; declaration types)
- [x] explicit coercion ASTNode, e.g. `Coerce { e: Box<expr>, src: Box<Type>, tgt: Box<Type> }` storing source and target types
- [ ] tests!!!!
  + [x] which syntax is accepted
  + [x] that the inference produces right answers
  + [ ] run tests in CI https://docs.github.com/en/actions
- [x] tcheck.rs to validate the final, fully substituted ast
- [x] `AstVariants` -> `AstNode`
- [x] `Trinary` -> `If` or `Ternary` (but lol who cares)
- [ ] separate cgen.rs (eventually)
- [ ] ~~steal https://github.com/nuprl/jankscripten/blob/main/libjankscripten/src/javascript/desugar.rs to work with a nicer subset of JS~~ desugaring corrupts the input source 😭 
- [ ] at some point: operations, with overloading as TS permits it (not all of JS!)
  ```ShellSession
  $echo "let x : string = '' + 3;" >test.ts ; tsc test.ts ; cat test.js
  var x = '' + 3;
  ```
- [ ] output `.d.ts` file (or rewrite the code to `.ts`... need to be preserving comments! might be able to do something clever with source maps to recover this, or we just need more concrete syntax tree)
